### ISSUE TITLE
Licensing/Copyright dicussion

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/mlonmcu-models#1]
Currently this repository is just a copy of the old `ml_on_mcu/data` directory. It definitely needs a lot of cleanup work (e.g. remove broken or irrelevant models)

I was wondering if we get into copyright problems when we are distributing third part models as soon as MLonMCU goes open source?

Should it be enough to just mention the original source of a `.tflite` file and some additional metadata such as the authors (if available) or do we need to decide this on a per-model basis?

@rafzi @DanMueGri

**Comment by rafzi** [comment]
As far as I know we have to check for every model, if the license permits reditribution and under which terms (e.g. copy original license information).

We could circumvent this by adding a download script that refers to the original sources.

**Comment by PhilippvK** [comment]
I am starting with the refactoring now using the following scheme:

- If a model is broken or was never used before remove it
- If a models was trained by us (e.g. test models), keep it as it is (However we should decide on a license for them and make sure that we provide the training scripts as well)
- For every other model note down their original source/author/licence
- Drop every model which shall not be redistributed or with missing license


Here is a up-to-date list of all models we have right now:

## from EDA@TUM

#### Trained models

Probably all trained by @alxhoff? We might reduce this to only relevant ones suitable for MCUs.

- [ ] ./simple_mnist/MNIST_best_model.tflite
- [ ] ./simple_mnist/MNIST_model.tflite
- [ ] ./simple_mnist/MNIST_model_quantized.tflite
- [ ] ./simple_mnist/model_data.tflite
- [ ] ./simple_mnist/model_data_pruned.tflite
- [ ] ./simple_mnist/model_data_size_optimized.tflite
- [ ] ./simple_mnist/simple_mnist.tflite
- [ ] ./simple_mnist/test_model3_alex.tflite

#### Tests

- [x] ./tests/custom/custom.tflite
- [x] ./tests/model_with_add/model_with_add.tflite
- [x] ./tests/model_with_add2/model_with_add2.tflite
- [x] ./tests/model_with_detection_postprocess/model_with_detection_postprocess.tflite
- [x] ./tests/model_with_detection_postprocess_static/model_with_detection_postprocess_static.tflite
- [x] ./tests/model_with_logistic/model_with_logistic.tflite
- [x] ./tests/model_with_multiple_outputs/model_with_multiple_outputs.tflite
- [x] ./tests/model_with_multiple_scratch_buffers/model_with_multiple_scratch_buffers.tflite
- [x] ./tests/model_with_reduce_max/model_with_reduce_max.tflite
- [x] ./tests/model_with_reverse_sequence/model_with_reverse_sequence.tflite
- [x] ./tests/model_with_reverse_sequence2/model_with_reverse_sequence2.tflite
- [x] ./tests/model_with_zero_out/model_with_zero_out.tflite

All trained by me, at some time we might use them for smoke-tests etc.

## from TFLM

They do not have a specific LICENSE, so its likely that the Apache 2.0 license of the project itself holds for those as well.

- [x] ./magic_wand/magic_wand.tflite
- [x] ./micro_speech/micro_speech.tflite
- [x] ./sine_model/sine_model.tflite



## from MLPerf Tiny
- [x] ./aww/aww.tflite
- [x] ./resnet/resnet.tflite
- [x] ./toycar/toycar.tflite
- [x] ./vww/vww.tflite

It seems like every model has its own LICENSE file which is fine.

## Unkown Source

@rafzi Do you know the difference between `catdog` and `catdog2`? Maybe we can decide to use only one of those. We should definitely make sure to keep `cifar10` as well as it is quite useful. I have no opinion on `bigsine_quant` and `lstm2`...

- [ ] ./bigsine_quant/bigsine_quant.tflite
- [ ] ./catdog/catdog.tflite
- [ ] ./catdog/CNN_2L_model_quantized.tflite
- [ ] ./catdog/CNN_full_quantized.tflite
- [ ] ./catdog/CNN_full_quantized_70_.tflite
- [ ] ./catdog/CNN_model.tflite
- [ ] ./catdog2/catdog2.tflite
- [ ] ./cifar10/cifar10.tflite
- [ ] ./lstm2/lstm2.tflite

Having two versions of MobileNetV2 is quiet confusing. Let's decide of a single one...

For TinyML those model are not relevant anyway, however we can keep them here as they can still be useful.

- [ ] ./mobilenetv1/mobilenetv1.tflite
- [ ] ./MobileNetV2/MobileNetV2.tflite
- [ ] ./MobileNetV2/MobileNet_V2.tflite

I added this one from the TensorflowHub so it should be able to find out its LICENSE. It use using the `Detection_POSTPROCESS` custom op as well as dynamic shapes and is therfore a good reference for testing: 
- [x] ./ssd/ssd.tflite



## Incompatible

Lets just get rid of those... Packing as a feature will at some time be added back to MLonMCU itself.

- [x] ./sine_model/sine_model_dummyquant.tflite
- [x] ./sine_model/sine_model_dummyquant_packed.tflite

## Non-tflite models

These models require preprocessing which is not yet supported in the new MLonMCU frontends. I would like to drop them for know. (They are still available in the history and the old version of mlonmcu)

- [x] ./KWS_CNN_S/KWS_CNN_S.pb (Source: https://github.com/ARM-software/ML-KWS-for-MCU)
- [x] ./cifar10_cnn/cifar10_cnn.pb
- [x] ./simple_graph/simple_graph.pb

**Comment by PhilippvK** [comment]
Regarding the reference to the original source I would like to go the same approach as done by ARM in their https://github.com/ARM-software/ML-zoo:

Add a `definition.yml` file containing all relevant metadata like in this example:

```yaml
benchmark:
  Google Speech Commands test set:
    Accuracy: 0.953
description: This is a fully quantized version (asymmetrical int8) of the MicroNet
  Small model developed by Arm, from the MicroNets paper. This model is trained on
  the 'Google Speech Commands' dataset.
license:
- Apache-2.0
network:
  file_size_bytes: 114512
  filename: kws_micronet_s.tflite
  framework: TensorFlow Lite
  hash:
    algorithm: sha1
    value: d13a25dbe34a0f2758879b9d3e7c7bad94c68ec7
  provenance: https://arxiv.org/pdf/2010.11267.pdf
network_parameters:
  input_nodes:
  - description: A one second audio clip, converted to a 2D MFCC computed from a speech
      frame of length 40ms and stride 20ms.
    example_input:
      path: models/keyword_spotting/micronet_small/tflite_int8/testing_input/input
    name: input
    shape:
    - 1
    - 49
    - 10
    - 1
  output_nodes:
  - description: The probability on 12 keywords.
    name: Identity
    shape:
    - 1
    - 12
    test_output_path: models/keyword_spotting/micronet_small/tflite_int8/testing_output/Identity
operators:
  TensorFlow Lite:
  - AVERAGE_POOL_2D
  - CONV_2D
  - DEPTHWISE_CONV_2D
  - RELU6
  - RESHAPE
paper: https://arxiv.org/pdf/2010.11267.pdf
```

This is very useful as it also document the used operators in the model as well as the input shapes which can be reused by MLonMCU. Additional information of the purpose of a model, its accurary,... can ce added if available. Even reference `inout` data an be specified in here.

I would prefer to just put the LICENSE name if that metadata file instead of copying over the `LICENSE` files everywhere.
